Repository marcosdosea/SOSCidadao, pull requests merged in 2021-01, with the labels that each got.

#84 Casos de uso Manter pertences e Definir tipos de Pessoas
  Requisitos/Casos de uso/Nível de Sistema/CSU08 - Manter Tipos de Pertence.docx
  Requisitos/Casos de uso/Nível de Sistema/CSU08 - Manter Tipos de pertences.docx
  Requisitos/Casos de uso/Nível de Sistema/CSU09 - Definir Tipo de Pessoa.docx
  Requisitos/Casos de uso/Nível de Sistema/CSU09 - Definir tipos de Usuario.docx
  Requisitos/Requisitos funcionais e nao funcionais.docx
  Requisitos/Requisitos funcionais e nao funcionais.docx.pdf
Labels: documentation

#75 Resolve #73. Alteração do DER, com os ajustes solicitados.
  AnaliseProjeto/Modelos do Sistema.mdj
Labels: documentation

#142 141
  Codigo/SosCidadaoWeb/Controllers/PertenceController.cs
  Codigo/SosCidadaoWeb/Views/Pertence/Create.cshtml
  Codigo/SosCidadaoWeb/Views/Pertence/Edit.cshtml
Labels: bug

#148 Permitir exibir o nome da organização ao em manter tipo ocorrência
  Codigo/Core/DTO/TipoocorrenciaDTO.cs
  Codigo/Core/Service/ITipoocorrenciaService.cs
  Codigo/Service/TipoocorrenciaService.cs
  Codigo/SosCidadaoWeb/Controllers/TipoocorrenciaController.cs
  Codigo/SosCidadaoWeb/Mappers/TipoocorrenciaProfile.cs
  Codigo/SosCidadaoWeb/Views/Tipoocorrencia/Delete_DTO.cshtml
  Codigo/SosCidadaoWeb/Views/Tipoocorrencia/Details_DTO.cshtml
  Codigo/SosCidadaoWeb/Views/Tipoocorrencia/Edit.cshtml
  Codigo/SosCidadaoWeb/Views/Tipoocorrencia/Index_DTO.cshtml
Labels: enhancement
